# -*- coding: utf-8 -*-
# Generated by the Protocol Buffers compiler - Python bindings for Tibia appearances.proto
# Based on: https://github.com/Arch-Mina/Assets-Editor/blob/main/Assets%20Editor/appearances.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf.internal import builder as _builder

# Protocol Buffers bindings - simplified pure Python version
# to avoid crashes with invalid serialized data

try:
    from google.protobuf import descriptor_pool
    # DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'...')
except ImportError:
    pass

# Force usage of Python dataclasses instead of generated protobuf code
# This avoids the "Couldn't parse file content" error
_APPEARANCES_FALLBACK = True

if '_APPEARANCES' not in dir() or True:  # Always use fallback
    import struct
    from dataclasses import dataclass, field
    from typing import List, Optional

    
    @dataclass
    class SpritePhase:
        duration_min: int = 0
        duration_max: int = 0
    
    @dataclass
    class SpriteAnimation:
        default_start_phase: int = 0
        synchronized: bool = False
        random_start_phase: bool = False
        loop_type: int = 0
        loop_count: int = 0
        sprite_phase: List[SpritePhase] = field(default_factory=list)
        animation_mode: int = 0
    
    @dataclass
    class Box:
        x: int = 0
        y: int = 0
        width: int = 0
        height: int = 0
    
    @dataclass
    class SpriteInfo:
        pattern_width: int = 1
        pattern_height: int = 1
        pattern_depth: int = 1
        layers: int = 1
        sprite_id: List[int] = field(default_factory=list)
        animation: Optional[SpriteAnimation] = None
        bounding_square: int = 32
        is_opaque: bool = False
        bounding_box_per_direction: List[Box] = field(default_factory=list)
        pattern_size: int = 32
        pattern_layers: int = 1
        pattern_x: int = 1
        pattern_y: int = 1
        pattern_z: int = 1
        pattern_frames: int = 1
        is_animation: bool = False
    
    @dataclass
    class FrameGroup:
        fixed_frame_group: int = 0
        id: int = 0
        sprite_info: Optional[SpriteInfo] = None
    
    @dataclass 
    class AppearanceFlagBank:
        waypoints: int = 0
    
    @dataclass
    class AppearanceFlagWrite:
        max_text_length: int = 0
    
    @dataclass
    class AppearanceFlagWriteOnce:
        max_text_length_once: int = 0
    
    @dataclass
    class AppearanceFlagLight:
        brightness: int = 0
        color: int = 0
    
    @dataclass
    class AppearanceFlagHeight:
        elevation: int = 0
    
    @dataclass
    class AppearanceFlagShift:
        x: int = 0
        y: int = 0
        a: int = 0
        b: int = 0
    
    @dataclass
    class AppearanceFlagClothes:
        slot: int = 0
    
    @dataclass
    class AppearanceFlagDefaultAction:
        action: int = 0
    
    @dataclass
    class AppearanceFlagMarket:
        category: int = 0
        trade_as_object_id: int = 0
        show_as_object_id: int = 0
        restrict_to_vocation: List[int] = field(default_factory=list)
        minimum_level: int = 0
        name: str = ""
        vocation: int = 0
    
    @dataclass
    class AppearanceFlagAutomap:
        color: int = 0
    
    @dataclass
    class AppearanceFlagLenshelp:
        id: int = 0
    
    @dataclass
    class AppearanceFlagChangedToExpire:
        former_object_typeid: int = 0
    
    @dataclass
    class AppearanceFlagCyclopedia:
        cyclopedia_type: int = 0
    
    @dataclass
    class AppearanceFlagUpgradeClassification:
        upgrade_classification: int = 0
    
    @dataclass
    class AppearanceFlags:
        bank: Optional[AppearanceFlagBank] = None
        clip: bool = False
        bottom: bool = False
        top: bool = False
        container: bool = False
        cumulative: bool = False
        usable: bool = False
        forceuse: bool = False
        multiuse: bool = False
        write: Optional[AppearanceFlagWrite] = None
        write_once: Optional[AppearanceFlagWriteOnce] = None
        liquidpool: bool = False
        unpass: bool = False
        unmove: bool = False
        unsight: bool = False
        avoid: bool = False
        no_movement_animation: bool = False
        take: bool = False
        liquidcontainer: bool = False
        hang: bool = False
        hook: int = 0
        rotate: bool = False
        light: Optional[AppearanceFlagLight] = None
        dont_hide: bool = False
        translucent: bool = False
        shift: Optional[AppearanceFlagShift] = None
        height: Optional[AppearanceFlagHeight] = None
        lying_object: bool = False
        animate_always: bool = False
        automap: Optional[AppearanceFlagAutomap] = None
        lenshelp: Optional[AppearanceFlagLenshelp] = None
        fullbank: bool = False
        ignore_look: bool = False
        clothes: Optional[AppearanceFlagClothes] = None
        default_action: Optional[AppearanceFlagDefaultAction] = None
        market: Optional[AppearanceFlagMarket] = None
        wrap: bool = False
        unwrap: bool = False
        topeffect: bool = False
        corpse: bool = False
        player_corpse: bool = False
        cyclopediaitem: Optional[AppearanceFlagCyclopedia] = None
        ammo: bool = False
        show_off_socket: bool = False
        reportable: bool = False
        upgradeclassification: Optional[AppearanceFlagUpgradeClassification] = None
        wearout: bool = False
        clockexpire: bool = False
        expire: bool = False
        expirestop: bool = False
        hook_south: bool = False
        hook_east: bool = False
    
    @dataclass
    class Appearance:
        id: int = 0
        frame_group: List[FrameGroup] = field(default_factory=list)
        flags: Optional[AppearanceFlags] = None
        name: str = ""
        description: str = ""
        appearance_type: int = 0
        sprite_data: List[bytes] = field(default_factory=list)
    
    @dataclass
    class SpecialMeaningAppearanceIds:
        gold_coin_id: int = 0
        platinum_coin_id: int = 0
        crystal_coin_id: int = 0
        tibia_coin_id: int = 0
        stamped_letter_id: int = 0
        supply_stash_id: int = 0
        standard_reward_chest_id: int = 0
    
    @dataclass
    class Appearances:
        object: List[Appearance] = field(default_factory=list)
        outfit: List[Appearance] = field(default_factory=list)
        effect: List[Appearance] = field(default_factory=list)
        missile: List[Appearance] = field(default_factory=list)
        special_meaning_appearance_ids: Optional[SpecialMeaningAppearanceIds] = None
        
        def ParseFromString(self, data: bytes):
            """Parse protobuf binary data - simplified implementation"""
            # This requires proper protobuf parsing
            # For now, we'll use the google.protobuf library to do the heavy lifting
            pass

# Enums
class FIXED_FRAME_GROUP:
    OUTFIT_IDLE = 0
    OUTFIT_MOVING = 1
    OBJECT_INITIAL = 2

class PLAYER_ACTION:
    NONE = 0
    LOOK = 1
    USE = 2
    OPEN = 3
    AUTOWALK_HIGHLIGHT = 4

class ITEM_CATEGORY:
    ARMORS = 1
    AMULETS = 2
    BOOTS = 3
    CONTAINERS = 4
    DECORATION = 5
    FOOD = 6
    HELMETS_HATS = 7
    LEGS = 8
    OTHERS = 9
    POTIONS = 10
    RINGS = 11
    RUNES = 12
    SHIELDS = 13
    TOOLS = 14
    VALUABLES = 15
    AMMUNITION = 16
    AXES = 17
    CLUBS = 18
    DISTANCE_WEAPONS = 19
    SWORDS = 20
    WANDS_RODS = 21
    PREMIUM_SCROLLS = 22
    TIBIA_COINS = 23
    CREATURE_PRODUCTS = 24
    QUIVER = 25
    SOUL_CORES = 26
    FIST_WEAPONS = 27

class VOCATION:
    ANY = -1
    NONE = 0
    KNIGHT = 1
    PALADIN = 2
    SORCERER = 3
    DRUID = 4
    MONK = 5
    PROMOTED = 10

class ANIMATION_LOOP_TYPE:
    PINGPONG = -1
    INFINITE = 0
    COUNTED = 1

class HOOK_TYPE:
    SOUTH = 1
    EAST = 2

class ANIMATION_ANIMATION_MODE:
    ASYNCHRONIZED = 0
    SYNCHRONIZED = 1

class APPEARANCE_TYPE:
    OBJECT = 1
    OUTFIT = 2
    EFFECT = 3
    MISSILE = 4
